# Generated by Django 3.0.11 on 2020-11-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mongodb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mongodb',
            name='connection_string',
        ),
        migrations.AddField(
            model_name='mongodb',
            name='db_name',
            field=models.CharField(default='hackerman', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mongodb',
            name='db_password',
            field=models.CharField(default='1234', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mongodb',
            name='db_user',
            field=models.CharField(default='user', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mongodb',
            name='srv',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=1024)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='mongodb.MongoDB')),
            ],
        ),
    ]
